sudo: required

language: python
python:
    - 3.6

install:
    - pip install -r requirements-dev.txt

script:
    - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then black --line-length 60 --check . ; fi
    - py.test

